---
title:
  - type: main
    text: REPLACE_DOCUMENT_TITLE
  - type: subtitle
    text: REPLACE_DOCUMENT_SUBTITLE
subject: 'Satzung des TTN Leipzig e.V.'
keywords:
  - Satzung
lang: 'de'
creator:
  - role: author
    text: REPLACE_DOCUMENT_AUTHOR
identifier:
  - scheme: DOI
    text: doi:10.234234.234/33
author:
  - TTN Leipzig GbR
  - André Lademann

date: '2025-04-01'
version: 'REPLACE_DOCUMENT_VERSION'
publisher: REPLACE_DOCUMENT_AUTHOR
rights: © 2025 TTN Leipzig e.V.

belongs-to-collection: offers
description: Satzung des TTN Leipzig e.V.
